version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/slashtechno/api-failover"

[[transformers]]
name = "gofmt"
enabled = true