name: Continuous Integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - id: commit
    #   uses: pr-mpt/actions-commit-hash@v1

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.18
    - name: Cross compile
      uses: crazy-max/ghaction-xgo@v2
      with:
        xgo_version: latest
        go_version: 1.19
        dest: /home/runner/work/api-failover/builds
        prefix: api-failover
        # targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64,windows/arm,windows/arm64,linux/arm,darwin/amd64
    - name: Compress releases
      run: zip -r /home/runner/work/api-failover/binaries.zip /home/runner/work/api-failover/builds/*
    # - name: Delete old release
    - name: Update tag
      uses: EndBug/latest-tag@latest
      with:
        ref: rolling
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Rolling release
        prerelease: true
        # tag_name: ${{ steps.commit.outputs.short }}
        tag_name: rolling
        # generate_release_notes: true
        body: "Latest commit: ${{ github.event.head_commit.message }}"
        files: |
          /home/runner/work/api-failover/binaries.zip 
          /home/runner/work/api-failover/builds/*
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: /home/runner/work/api-failover/builds/*
        retention-days: 2
